spring.application.name=print-service
server.port=8084

spring.datasource.url=jdbc:postgresql://postgresql:5432/is_print
#spring.datasource.url=jdbc:postgresql://localhost:5432/is_print
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:liquibase-changelog.xml
spring.liquibase.enabled=true

logging.level.liquibase=DEBUG

#spring.cloud.consul.host=localhost
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.enabled=true
#spring.cloud.consul.discovery.register=true
#spring.cloud.consul.discovery.service-name=${spring.application.name}

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8181}/realms/cloud-realm
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://34.116.235.108/realms/garment_print

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

#frontend-url=http://localhost:3000
#frontend-url=http://frontend:80